#!/usr/bin/env python3
"""Render a week's summaries into one navigable HTML page.

Summaries live in out/<ISO-week>/<video-id>.md with a small front-matter block.
Rendering is dependency-free: the summary markdown is generated by us, so it uses
a constrained subset (headings, emphasis, links, lists, rules, timestamp spans).
"""
import re, sys, os, json, html, datetime, glob

TIME = re.compile(r'^\d{1,2}:\d{2}(:\d{2})?$')
CONTEST = re.compile(r'comments contest', re.I)


def iso_week(d=None):
    d = d or datetime.date.today()
    y, w, _ = d.isocalendar()
    return f'{y}-W{w:02d}'


def week_label(tag):
    y, w = int(tag[:4]), int(tag[6:])
    mon = datetime.date.fromisocalendar(y, w, 1)
    sun = datetime.date.fromisocalendar(y, w, 7)
    if mon.month == sun.month:
        return f'{mon:%-d}–{sun:%-d} {mon:%B %Y}'
    return f'{mon:%-d %b} – {sun:%-d %b %Y}'


def parse(path):
    """Split front matter from body."""
    raw = open(path, encoding='utf-8').read()
    meta, body = {}, raw
    if raw.startswith('---\n'):
        head, _, body = raw[4:].partition('\n---\n')
        for line in head.splitlines():
            if ':' in line:
                k, _, v = line.partition(':')
                meta[k.strip()] = v.strip()
    return meta, body.strip()


def inline(s):
    """Inline markdown -> HTML. Escapes first, so no raw HTML passes through."""
    s = html.escape(s, quote=False)
    # `code` -- a bare timestamp becomes a jump chip
    def code(m):
        t = m.group(1)
        cls = 'ts' if TIME.match(t) else 'mono'
        return f'<span class="{cls}">{t}</span>'
    s = re.sub(r'`([^`]+)`', code, s)
    s = re.sub(r'\[([^\]]+)\]\(([^)]+)\)', r'<a href="\2">\1</a>', s)
    s = re.sub(r'\*\*([^*]+)\*\*', r'<strong>\1</strong>', s)
    s = re.sub(r'(?<!\*)\*([^*]+)\*(?!\*)', r'<em>\1</em>', s)
    return s


def to_html(md):
    """Block-level markdown -> HTML."""
    out, lines, i = [], md.split('\n'), 0
    para, items, quote, contested = [], [], [], [False]

    def flush():
        if para:
            out.append('<p>' + inline(' '.join(para)) + '</p>'); para.clear()
        if items:
            out.append('<ul>' + ''.join(f'<li>{inline(x)}</li>' for x in items) + '</ul>')
            items.clear()
        if quote:
            out.append('<blockquote>' + inline(' '.join(quote)) + '</blockquote>'); quote.clear()

    while i < len(lines):
        ln = lines[i].rstrip()
        if not ln.strip():
            flush()
        elif ln.startswith('#'):
            flush()
            lvl = len(ln) - len(ln.lstrip('#'))
            txt = ln.lstrip('# ').strip()
            if CONTEST.search(txt):          # always the closing section
                flush()
                out.append('<section class="contested"><h3>' + inline(txt) + '</h3>')
                contested[0] = True
            else:
                tag = {1: 'h4', 2: 'h4', 3: 'h5', 4: 'h5'}.get(lvl, 'h5')
                out.append(f'<{tag}>{inline(txt)}</{tag}>')
        elif ln.strip() == '---':
            flush()
        elif ln.lstrip().startswith(('- ', '* ')):
            if para: flush()
            items.append(ln.lstrip()[2:].strip())
        elif ln.startswith('> '):
            if para or items: flush()
            quote.append(ln[2:].strip())
        elif items and ln.startswith(('  ', '\t')):
            items[-1] += ' ' + ln.strip()          # continuation of a list item
        else:
            if items or quote: flush()
            para.append(ln.strip())
        i += 1
    flush()
    if contested[0]:
        out.append('</section>')
    return '\n'.join(out)


def slug(meta, vid):
    base = re.sub(r'[^a-z0-9]+', '-', (meta.get('title') or vid).lower()).strip('-')
    return base[:40] or vid


def render(week_dir, tag):
    files = sorted(glob.glob(os.path.join(week_dir, '*.md')))
    if not files:
        raise SystemExit('no summaries in ' + week_dir)
    entries = []
    for f in files:
        meta, body = parse(f)
        vid = os.path.splitext(os.path.basename(f))[0]
        entries.append((vid, meta, body, slug(meta, vid)))
    # newest first by added date when present
    entries.sort(key=lambda e: e[1].get('added', ''), reverse=True)

    tpl = open(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                            'page.html'), encoding='utf-8').read()

    nav = ''.join(f'<a href="#{s}">{html.escape(m.get("nav") or m.get("title","")[:28])}</a>'
                  for _, m, _, s in entries)

    arts = []
    for vid, m, body, s in entries:
        kick = ''.join(f'<span>{html.escape(m[k])}</span>'
                       for k in ('channel', 'duration', 'views') if m.get(k))
        cost = ' &middot; '.join(filter(None, [
            f'<b>{html.escape(m["watchable"])}</b> worth watching' if m.get('watchable') else '',
            f'<b>{html.escape(m["fluff"])} fluff</b>' if m.get('fluff') else '',
            html.escape(m['compression']) if m.get('compression') else '']))
        arts.append(
            f'<article id="{s}">\n<div class="kicker">{kick}</div>\n'
            f'<h2>{inline(m.get("title", vid))}</h2>\n'
            f'<div class="verdict"><p>{inline(m.get("verdict",""))}</p>'
            f'<p class="cost">{cost}</p></div>\n'
            f'<a class="src" href="https://youtu.be/{vid}">watch on YouTube &rarr;</a>\n'
            f'{to_html(body)}\n</article>')

    return (tpl.replace('{{WEEK}}', week_label(tag))
               .replace('{{TAG}}', tag)
               .replace('{{COUNT}}', str(len(entries)))
               .replace('{{NAV}}', nav)
               .replace('{{ARTICLES}}', '\n'.join(arts)))


if __name__ == '__main__':
    tag = sys.argv[1] if len(sys.argv) > 1 else iso_week()
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    wdir = os.path.join(root, 'out', tag)
    out = os.path.join(wdir, 'index.html')
    open(out, 'w', encoding='utf-8').write(render(wdir, tag))
    print(out)
